In [3]:
#以下3行ipynbファイルをimportするための記述．importファイルの更新はこのファイルを一度shutdownして実行し直すことで可能
import sys
import notebookutil as nbu
sys.meta_path.append(nbu.NotebookFinder())
from populationParallel import POPULATION

from RobotParallelHill import ROBOT
from individualParallelHill import INDIVIDUAL

#import pickle
#import copy
#import pyrosim
#import random
#import numpy
#import matplotlib.pyplot as plt

pop = POPULATION()
pop.Evaluate()


#parent = INDIVIDUAL()
#parent.Evaluate(True)
#print(parent.fitness)
    
#for i in range(0,10):
    #child = copy.deepcopy( parent )
    #child.Mutate()
    #child.Evaluate(True)
    #print('[g:' , i+1 , ']','[pw:' , parent.genome, ']','[p:' , parent.fitness , ']','[c:' , child.fitness , ']' )
    #if ( child.fitness > parent.fitness ):
            #parent = child
            #parent.Evaluate(False)
            #parent.Evaluate(True)
            #f = open('robot.p', 'wb')
            #pickle.dump(parent , f )
            #f.close()
    
    
    
    
    

[ 0.10192931 -0.50758543  0.72007362 -0.19851476]
[-0.42492665  0.77653717 -0.27604152  0.65441915]
[ 0.86246423 -0.80598713  0.43440546  0.82757468]
[-0.03741086  0.08483567 -0.41291818  0.68333183]
[ 0.69888141 -0.22868645  0.74510991  0.57664825]
